// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:restaurant_app/core/db/hive/model_address.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ModelAddressAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ModelAddressAdapter());
  }
}
